#!/usr/bin/env python3
"""
Social Media Poster
===================
Posts hiking reel videos to Instagram and TikTok with captions, hashtags,
and scheduled posting times using the Late (getlate.dev) API.

Late handles both platforms in a single API call and manages video
transcoding, scheduling, and delivery.

Setup:
    1. Sign up at https://getlate.dev
    2. Connect your Instagram Business and TikTok accounts
    3. Get your API key from the dashboard
    4. Set it as an environment variable: export LATE_API_KEY="your-key"

Usage:
    python post_to_social.py \
        --video "output/sedona-reel.mp4" \
        --hike-folder "~/Hiking Content/2026-02-15-sedona" \
        --platforms instagram tiktok \
        --schedule "2026-02-18T11:00:00-05:00"

Requirements:
    pip install requests
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

LATE_API_BASE = "https://api.getlate.dev/v1"


def get_api_key():
    """Get the Late API key from environment."""
    key = os.environ.get("LATE_API_KEY")
    if not key:
        print("ERROR: LATE_API_KEY environment variable not set.")
        print("  1. Sign up at https://getlate.dev")
        print("  2. Get your API key from the dashboard")
        print("  3. Run: export LATE_API_KEY='your-key-here'")
        sys.exit(1)
    return key


def load_caption_data(hike_folder):
    """Load trail data and look for a captions file."""
    folder = Path(hike_folder)

    # Load trail data
    trail_data_path = folder / "trail-data.json"
    if trail_data_path.exists():
        with open(trail_data_path) as f:
            trail_data = json.load(f)
    else:
        trail_data = {}

    # Check for a captions file (generated by Claude)
    captions_path = folder / "captions.json"
    if captions_path.exists():
        with open(captions_path) as f:
            return json.load(f)

    # Build default captions from trail data
    name = trail_data.get("trail_name", "Trail")
    location = trail_data.get("location", "")
    rating = trail_data.get("alltrails_rating")
    difficulty = trail_data.get("difficulty")
    quote = trail_data.get("quote")
    tags = trail_data.get("tags", [])

    # Build location line
    location_line = f"📍 {name}"
    if location:
        location_line += f", {location}"

    # Build info line
    if rating:
        info_parts = [f"⭐ {rating} on AllTrails"]
        if difficulty:
            info_parts.append(difficulty)
        info_line = " | ".join(info_parts)
    elif quote:
        info_line = f'"{quote}"'
    else:
        info_line = ""

    # Default Instagram caption
    ig_caption = f"{name} ✨\n\n{location_line}\n{info_line}"
    ig_hashtags = build_default_hashtags(name, location, tags, "instagram")

    # Default TikTok caption (shorter)
    tt_caption = f"POV: hiking {name} 🥾"
    tt_hashtags = build_default_hashtags(name, location, tags, "tiktok")

    return {
        "instagram": {
            "caption": f"{ig_caption}\n\n{ig_hashtags}",
        },
        "tiktok": {
            "caption": f"{tt_caption} {tt_hashtags}",
        },
    }


def build_default_hashtags(trail_name, location, tags, platform):
    """Build default hashtags when no custom captions are available."""
    hashtags = ["#hiking"]

    if platform == "tiktok":
        hashtags.append("#hikertok")
    else:
        hashtags.append("#hikingadventures")

    # Location-based hashtag
    if location:
        state = location.split(",")[-1].strip().lower().replace(" ", "")
        hashtags.append(f"#{state}hiking")

    # Feature-based hashtag
    if tags:
        hashtags.append(f"#{tags[0].replace('-', '')}")

    # Trail-specific hashtag
    trail_tag = trail_name.lower().replace(" ", "").replace("'", "")
    if len(trail_tag) < 30:
        hashtags.append(f"#{trail_tag}")

    return " ".join(hashtags[:5])


def get_connected_profiles(api_key):
    """List connected social media profiles."""
    response = requests.get(
        f"{LATE_API_BASE}/profiles",
        headers={"Authorization": f"Bearer {api_key}"},
        timeout=10,
    )
    response.raise_for_status()
    return response.json()


def upload_and_post(
    api_key, video_path, caption_data, platforms, schedule_time=None
):
    """Upload video and create posts on specified platforms."""
    video_path = Path(video_path)
    if not video_path.exists():
        print(f"ERROR: Video file not found: {video_path}")
        sys.exit(1)

    # Get connected profiles
    print("Checking connected accounts...")
    profiles = get_connected_profiles(api_key)

    platform_profiles = {}
    for profile in profiles.get("data", []):
        ptype = profile.get("platform", "").lower()
        if ptype in platforms:
            platform_profiles[ptype] = profile
            print(f"  Found: {ptype} — @{profile.get('username', 'unknown')}")

    missing = set(platforms) - set(platform_profiles.keys())
    if missing:
        print(f"\nWARNING: These platforms are not connected: {', '.join(missing)}")
        print("  Connect them at https://app.getlate.dev/profiles")

    if not platform_profiles:
        print("ERROR: No connected profiles found for the requested platforms.")
        sys.exit(1)

    # Post to each platform
    results = {}
    for platform, profile in platform_profiles.items():
        caption = caption_data.get(platform, {}).get(
            "caption", caption_data.get("instagram", {}).get("caption", "")
        )

        print(f"\nPosting to {platform}...")
        print(f"  Caption: {caption[:100]}...")
        if schedule_time:
            print(f"  Scheduled for: {schedule_time}")

        # Upload video
        with open(video_path, "rb") as video_file:
            post_data = {
                "profile_id": profile["id"],
                "caption": caption,
                "media_type": "video",
            }

            if schedule_time:
                post_data["scheduled_at"] = schedule_time

            response = requests.post(
                f"{LATE_API_BASE}/posts",
                headers={"Authorization": f"Bearer {api_key}"},
                data=post_data,
                files={"media": (video_path.name, video_file, "video/mp4")},
                timeout=120,
            )

        if response.status_code in (200, 201):
            result = response.json()
            post_id = result.get("data", {}).get("id", "unknown")
            status = result.get("data", {}).get("status", "unknown")
            print(f"  Success! Post ID: {post_id}, Status: {status}")
            results[platform] = {"success": True, "post_id": post_id}
        else:
            print(f"  ERROR ({response.status_code}): {response.text[:200]}")
            results[platform] = {"success": False, "error": response.text[:200]}

    return results


def suggest_post_time(platform):
    """Suggest optimal posting times for hiking/outdoor content."""
    # Based on general social media engagement data for outdoor niche
    now = datetime.now(timezone.utc)
    suggestions = {
        "instagram": {
            "best_days": ["Tuesday", "Wednesday", "Thursday"],
            "best_hours": "11 AM - 1 PM or 7 PM - 9 PM (local time)",
            "reasoning": "Mid-week lunch breaks and evening browsing peaks",
        },
        "tiktok": {
            "best_days": ["Tuesday", "Thursday", "Saturday"],
            "best_hours": "7 PM - 10 PM (local time)",
            "reasoning": "After-work browsing and weekend planning",
        },
    }
    return suggestions.get(platform, {})


def main():
    parser = argparse.ArgumentParser(
        description="Post hiking reel to Instagram and TikTok via Late API"
    )
    parser.add_argument(
        "--video",
        required=True,
        help="Path to the video file to post",
    )
    parser.add_argument(
        "--hike-folder",
        required=True,
        help="Path to hike folder (for captions/trail data)",
    )
    parser.add_argument(
        "--platforms",
        nargs="+",
        default=["instagram", "tiktok"],
        choices=["instagram", "tiktok"],
        help="Platforms to post to (default: both)",
    )
    parser.add_argument(
        "--schedule",
        default=None,
        help="ISO 8601 datetime to schedule post (e.g., '2026-02-18T11:00:00-05:00')",
    )
    parser.add_argument(
        "--suggest-times",
        action="store_true",
        help="Show suggested posting times and exit",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be posted without actually posting",
    )

    args = parser.parse_args()

    if args.suggest_times:
        print("Suggested posting times for hiking content:\n")
        for platform in ["instagram", "tiktok"]:
            info = suggest_post_time(platform)
            print(f"  {platform.upper()}:")
            print(f"    Best days:  {', '.join(info['best_days'])}")
            print(f"    Best hours: {info['best_hours']}")
            print(f"    Why:        {info['reasoning']}")
            print()
        return

    hike_folder = os.path.expanduser(args.hike_folder)
    caption_data = load_caption_data(hike_folder)

    if args.dry_run:
        print("=== DRY RUN ===\n")
        print(f"Video: {args.video}")
        print(f"Platforms: {', '.join(args.platforms)}")
        if args.schedule:
            print(f"Schedule: {args.schedule}")
        print()
        for platform in args.platforms:
            cap = caption_data.get(platform, {}).get("caption", "(no caption)")
            print(f"--- {platform.upper()} ---")
            print(cap)
            print()
        return

    api_key = get_api_key()
    results = upload_and_post(
        api_key=api_key,
        video_path=args.video,
        caption_data=caption_data,
        platforms=args.platforms,
        schedule_time=args.schedule,
    )

    print("\n=== Summary ===")
    for platform, result in results.items():
        status = "✓" if result["success"] else "✗"
        print(f"  {status} {platform}: {result.get('post_id', result.get('error', ''))}")


if __name__ == "__main__":
    main()
